<?php

declare(strict_types=1);

namespace App\Modules\Comunicados;

use App\Modules\BaseModule;

/**
 * Module: Comunicados
 *
 * Auto-generated by make:module command.
 */
class ComunicadosModule extends BaseModule
{
    protected string $version = '1.0.0';
    protected bool $isCore = false;

    public function getId(): string
    {
        return 'comunicados';
    }

    public function getName(): string
    {
        return 'Comunicados';
    }

    public function getDescription(): string
    {
        return 'Gerenciamento de comunicados.';
    }

    public function getIcon(): string
    {
        return 'FileText';
    }

    public function getDependencies(): array
    {
        return [];
    }

    // ========================================
    // Statuses
    // ========================================

    public function getStatuses(): array
    {
        return [
            1 => [
                'name' => 'rascunho',
                'label' => 'Rascunho',
                'color' => 'gray',
                'icon' => 'FileEdit',
                'final' => false,
            ],
            2 => [
                'name' => 'publicado',
                'label' => 'Publicado',
                'color' => 'green',
                'icon' => 'Eye',
                'final' => false,
            ],
            3 => [
                'name' => 'arquivado',
                'label' => 'Arquivado',
                'color' => 'slate',
                'icon' => 'Archive',
                'final' => true,
            ],
        ];
    }

    // ========================================
    // Transitions
    // ========================================

    public function getTransitions(): array
    {
        return [
            1 => [2],       // Rascunho → Publicado
            2 => [3],       // Publicado → Arquivado
            3 => [],        // Arquivado (final)
        ];
    }

    // ========================================
    // Permissions
    // ========================================

    public function getPermissions(): array
    {
        return [
            ['name' => 'comunicados.view', 'display_name' => 'Ver Comunicados', 'type' => 'ability'],
            ['name' => 'comunicados.create', 'display_name' => 'Criar Comunicado', 'type' => 'ability'],
            ['name' => 'comunicados.update', 'display_name' => 'Editar Comunicado', 'type' => 'ability'],
            ['name' => 'comunicados.delete', 'display_name' => 'Excluir Comunicado', 'type' => 'ability'],
        ];
    }

    // ========================================
    // Actions
    // ========================================

    public function getActions(): array
    {
        return [
            'update_status' => [
                'label' => 'Atualizar Status',
                'icon' => 'RefreshCw',
                'permission' => 'comunicados.update',
            ],
        ];
    }

    // ========================================
    // Texts
    // ========================================

    public function getTexts(): array
    {
        return [
            'menu_label' => 'Comunicados',
            'menu_tooltip' => 'Gerenciar comunicados',
            'page_title' => 'Comunicados',
            'page_description' => 'Gerencie os comunicados do sistema',
            'create_button' => 'Novo Comunicado',
            'empty_state' => 'Nenhum comunicado encontrado.',
        ];
    }

    // ========================================
    // Screens
    // ========================================

    public function getScreens(): array
    {
        return [
            ['name' => 'comunicados.list', 'display_name' => 'Lista de Comunicados', 'path' => '/comunicados'],
            ['name' => 'comunicados.create', 'display_name' => 'Criar Comunicado', 'path' => '/comunicados/new'],
            ['name' => 'comunicados.edit', 'display_name' => 'Editar Comunicado', 'path' => '/comunicados/:id'],
        ];
    }

    // ========================================
    // Transition Role Matrix
    // ========================================

    public function getTransitionRoleMatrix(): array
    {
        return [
            1 => [
                2 => ['admin', 'super-admin'], // Rascunho → Publicado
            ],
            2 => [
                3 => ['admin', 'super-admin'], // Publicado → Arquivado
            ],
        ];
    }
}
